### ISSUE TITLE
feat: allow images to be added to the lectures

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/codetap.academy#101]
* we want to be able to add images to the lecture using and upload button
* ideally the images should be uploaded to firebase

**Comment by marianzburlea** [comment]
I've updated the description

**Comment by marianzburlea** [comment]
https://www.google.com/search?q=how+to+upload+images+to+firebase

**Comment by QuintyHH** [comment]
Clarification required:

1. When are you supposed to add the image, during the Add lecture process?
2. Where are they supposed to be displayed, on the individual lecture page?

**Comment by marianzburlea** [comment]
> Clarification required:
> 
> 1. When are you supposed to add the image, during the Add lecture process?
> 2. Where are they supposed to be displayed, on the individual lecture page?

On the lecture page (once you clicked on the lecture from the section area in a course)

**Comment by marianzburlea** [comment]
It's more important for the process to work and be refined later.

**Comment by QuintyHH** [comment]
![Capture](https://user-images.githubusercontent.com/42803595/62124491-0ac46f00-b2d3-11e9-99cd-747a03e2b55e.PNG)

Something along these lines?

**Comment by marianzburlea** [comment]
> ![Capture](https://user-images.githubusercontent.com/42803595/62124491-0ac46f00-b2d3-11e9-99cd-747a03e2b55e.PNG)
> 
> Something along these lines?

the image start is OK.
The place is wrong.
![image](https://user-images.githubusercontent.com/1318985/62124536-64706d80-b2c2-11e9-9860-5721e69e474d.png)
https://dev.codetap.academy/lecture/LOZuEiZZa4N5DEnHVrbW

**Comment by QuintyHH** [comment]
guess that makes more sense hahaha

**Comment by QuintyHH** [comment]
![Capture2](https://user-images.githubusercontent.com/42803595/62127099-e91ab600-b2d9-11e9-80f0-fbacf275fedf.PNG)

So I wrote down the logic, but I can't really go any further. I need a reference folder where I can save the images to, but when I try and create one, I get kicked out with:

![Capture3](https://user-images.githubusercontent.com/42803595/62127160-14050a00-b2da-11e9-8ce7-4521e0e8d033.PNG)

If you can create it, please name it "lecture-pictures".
We can tackle this one together tonight :)

**Comment by marianzburlea** [comment]
It's done.

**Comment by marianzburlea** [comment]
It didn't need a name
