### ISSUE TITLE
Set rules for Firebase Storage

### ISSUE THREAD

**Issue by QuintyHH** [codetapacademy/codetap.academy#111]
This is quite important since, at the moment, anyone and their mothers can upload images to the storage.

**Comment by marianzburlea** [comment]
That's true, nobody would do that as if somebody would care, CodeTap would be different :)
NOBODY cares about our website :)
People are selfish in general and only mind their own business.

**Comment by marianzburlea** [comment]
I believe setting up rules would be a good exercise for our team.

**Comment by QuintyHH** [comment]
I've partially implemented a ruleset that only allows admins to upload images. 
The problem is I cannot access the DB from storage, so they only reasonable way I found to do this is to hardcode Admin uid's into the ruleset.
