### ISSUE TITLE
feat: implement internationalisation

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/codetap.academy#123]

**Comment by tandaraelena** [comment]
documentation regarding internalisation: 
https://www.youtube.com/watch?v=RbsH7V437tE&t=415s
https://react.i18next.com/

**Comment by tandaraelena** [comment]
react-intl package updated: 
https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#breaking-api-changes

**Comment by robertoalx** [comment]
Another example of react-intl.
https://egghead.io/courses/add-internationalization-i18n-to-a-react-app-using-react-intl
