### ISSUE TITLE
feat: create an additional comment section to the video form

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/codetap.academy#163]
create an additional comment section to the video form

This issue is part of **feat: comments on the video page** #158

**Comment by tandaraelena** [comment]
documentation: 
https://medium.com/@aghh1504/1-simple-react-todo-list-52186b62976b
https://www.pusher.com/tutorials/todo-app-react-hooks#creating-a-new-task
https://scotch.io/tutorials/build-a-react-to-do-app-with-react-hooks-no-class-components#toc-reading-a-list-of-items-crud-
https://www.freecodecamp.org/news/how-to-build-a-todo-list-with-react-hooks-ebaa4e3db3b/
best: https://samderlust.com/dev-blog/javascript/reactjs-making-a-simple-todo-app-with-react-hooks
