### ISSUE TITLE
feat: add oncontextmenu false for video players

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/codetap.academy#187]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by QuintyHH** [comment]
document.getElementsByTagName("body")[0].oncontextmenu = function(e){ e.preventDefault();}  -- general way of disabling oncontextmenu, needs to be personalized for the video player...?

**Comment by marianzburlea** [comment]
@QuintyHH, it only needs to be added to the video player area, and we know which one it is as we've worked with a ratio of 16/9 :)

**Comment by QuintyHH** [comment]
yeah yeah just select THAT element instead of body, its pretty easy
