### ISSUE TITLE
fix: Uncaught (in promise) TypeError: Cannot read property 'isAdmin' of undefined

### ISSUE THREAD

**Issue by iuliancarnaru** [codetapacademy/codetap.academy#230]
When I press the button `Let me in` I get an error in console:

Uncaught (in promise) TypeError: Cannot read property 'isAdmin' of undefined

<img width="978" alt="Screen Shot 2019-09-16 at 11 29 55" src="https://user-images.githubusercontent.com/35683015/64951659-5082ca00-d876-11e9-8dcf-7c240f773b84.png">

**Comment by marianzburlea** [comment]
![image](https://user-images.githubusercontent.com/1318985/64951652-4e207000-d876-11e9-9c60-0f8cb27e31af.png)
