### ISSUE TITLE
feat: watch history

### ISSUE THREAD

**Issue by gratielazburlea** [codetapacademy/codetap.academy#326]
**Is your feature request related to a problem? Please describe.**
When I am on the page to watch the lessons and come back after some time I do not know how much I saw or how much of the lesson I watched
**Describe the solution you'd like**
Add an icon with an eye or background to indicate the progress of a lesson
**Describe alternatives you've considered**

**Additional context**

**Comment by marianzburlea** [comment]
Let's see if any of our codetap students will jump to help
