### ISSUE TITLE
fix: history gaps

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/codetap.academy#335]
**Describe the bug**

**To Reproduce**
1. Go to any course
1. Click on the play video button
1. Wait some time and notice that the playback jumps a second in the history

**Expected behavior**
A continuous playback should produce no gaps in history.

**Screenshots**
![image](https://user-images.githubusercontent.com/1318985/72652369-69170400-397e-11ea-998d-17c57f5f305c.png)

Implement logic to make sure delays don't cause a 0.9 time to jump to 2.1 instead of 1.9.

**Comment by gratielazburlea** [comment]
I can confirm the gaps
![image](https://user-images.githubusercontent.com/12233851/72652503-040fde00-397f-11ea-859e-62b3f30558fd.png)
